name: test_coda
description: Test for Coda
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  blur: ^3.0.0
  dotted_decoration: ^2.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/DMSans/DMSans-Italic.ttf
          weight: 400
          style: italic